name: Build Static Webapp

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build webapp
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x' # Only upload once
      with:
        name: grid-life-build
        path: dist/
        retention-days: 30
        
    - name: Check build output
      if: matrix.node-version == '20.x'
      run: |
        echo "Build completed successfully!"
        echo "Build artifacts:"
        ls -la dist/
        echo "Build size:"
        du -sh dist/ 